config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show] 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'posts/store' => 'posts#store'
  get 'posts/food' => 'posts#food'
  get 'posts/animal' => 'posts#animal'
  
  resources :posts do
    resources :likes, only: [:create, :destroy]
  end

  root 'posts#top'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
    mount_uploader :image, ImageUploader

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :post_tag_relations, dependent: :destroy
  has_many :tags, through: :post_tag_relations, dependent: :destroy

end

app/models/post_tag_relation.rb
class PostTagRelation < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true
  has_many :post_tag_relations, dependent: :destroy
  has_many :posts, through: :post_tag_relations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy 
  validates :name, presence: true
  validates :profile, length: { maximum: 200 } 
  
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters

    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
  end
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    like = current_user.likes.create(post_id: params[:post_id]) 
    redirect_back(fallback_location: root_path)
  end

  def destroy
    like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]
    def top
    end
    
    def index
        @posts = Post.all

        if params[:tag_ids]
          @posts = []
          params[:tag_ids].each do |key, value|      
            @posts += Tag.find_by(name: key).posts if value == "1"
          end
          @posts.uniq!
        end

        if params[:tag]
          Tag.create(name: params[:tag])
        end

        if params[:search] == nil
          @post = params[:tag_id].present? ? Tag.find(params[:tag_id]).posts : Post.all
        elsif params[:search] == ''
          @post = params[:tag_id].present? ? Tag.find(params[:tag_id]).posts : Post.all
        else

          @post = Post.where("storename LIKE ? OR menu LIKE ? OR place LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
        end

    end
    
    def new
        @post = Post.new
      end
    
      def create
        post = Post.new(post_params)

        post.user_id = current_user.id

        if post.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end
    
      def show
        @post = Post.find(params[:id])
      end

      def edit
        @post = Post.find(params[:id])
      end

      def update
        post = Post.find(params[:id])
        if post.update(post_params)
          redirect_to :action => "show", :id => post.id
        else
          redirect_to :action => "new"
        end
      end

      def destroy
        post = Post.find(params[:id])
        post.destroy
        redirect_to action: :index
      end

      def store
        @posts = Post.all
      end
    
      def food
        @posts = Post.all
      end
    
      def animal
        @posts = Post.all
      end

      private
       def post_params
         params.require(:post).permit(:image, :comment, :place, :category, :body, tag_ids: [])
       end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id]) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aiueo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/5d76b9a411.js"  crossorigin="anonymous"></script> 

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kaisei+Tokumin:wght@500&family=Zen+Kaku+Gothic+New&family=Zen+Maru+Gothic:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="stylesheets/index.css">
  </head>

<body>
 <header>
  <h1>散歩</h1>
  <div class="header-list">
   <ul>
    <% if user_signed_in? %>
     <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
     <li><%= link_to "トップページへ", root_path %></li>
     <li><%= link_to "新規投稿へ", new_post_path %></li>
    <% else %>
     <li><%= link_to "新規登録", new_user_registration_path %></li>
     <li><%= link_to "ログイン", new_user_session_path %></li>
    <% end %>
   </ul>
  </div>
 </header>
 <main>
  <%= yield %>
 </main>
</body>

</html>

app/views/layouts/posts/new.html.erb
<h1>散歩</h1>
<h3>新規投稿</h3>
<%= form_for @post do |f| %>

    <%= stylesheet_link_tag 'new', :media => "all" %>

    <div class="field">
      <%= f.label :画像 %><br />
      <%= f.file_field :image, class: "image" %>
    </div>

    # データ型がstringで自由記述の入力フォーム
    <div class="field">
      <%= f.label :場所 %>
      <%= f.text_field :place, :size => 30 %>
    </div>

    # データ型がtextで自由記述の入力フォーム
    <div class="field">
      <%= f.label :コメント %>
      <%= f.text_area :comment, :size => "30x2" %>
    </div>

    <%= f.submit "投稿する" %>
  <% end %>

  <%= link_to "一覧に戻る", posts_path %>

app/views/posts/animal.html.erb
<link rel="stylesheet" type="text/css" href="index.css">

<h1>動物</h1>

<div class="posts-container">
<% @posts.each do |t| %>
  <% if t.category == "animal" %>  

    <div class="post">
     <div class="image">
       <%= t.user.email %>
       <%= image_tag t.image_url, size: "280x210" if t.image? %>
     </div> 
     <%= t.category %>
     <%= t.place %>
     <%= t.create_date %>
     <%= t.comment %>
     <% t.tags.each do |tag| %>
       <span><%= tag.name %></span>
     <% end %>

     <p><%= link_to "詳細へ", post_path(t.id) %> 

     <% if user_signed_in? && current_user.id == t.user_id %>
     <%= link_to "編集する", edit_post_path(t.id) %>
     <%= button_to "削除する", post_path(t.id), method: :delete %> 
     <% end %> 

    <% if user_signed_in? %>
        <% if current_user.already_liked?(t) %>
          <%= link_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
              <i class="fas fa-heart"></i><%= t.likes.count %>
          <% end %>
        <% else %>
          <%= link_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
            <i class="far fa-heart"></i><%= t.likes.count %>
          <% end %>
        <% end %>
    <% else %>
      <i class="far fa-heart"></i><%= t.likes.count %>
    <% end %>

    </div>

  <% end %>
<% end %>

app/views/posts/edit.html.erb
<%= stylesheet_link_tag 'new', :media => "all" %>

<%= form_for @post do |f| %>
  <div class="form-group">
    <%= f.label :content,"ジャンル" %>
    <%= f.select :category, [["お店", "store"], ["ごはん", "food"], ["動物", "animal"]], include_blank: "どの投稿？" %>
  </div> 

  <div class="field">
    <%= f.label :どこ %>
    <%= f.text_field :place, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :写真 %><br>
    <%= f.file_field :image, class: "image" %>
  </div>
  <div id="image-list"></div>

  <div class="form-group">
    <%= f.label :いつ, class: 'control-label' %>
    <p><%= f.date_select :create_date, class: 'form-control' %></p>
  </div>

  <div class="field">
    <%= f.label :コメント  %>
    <%= f.text_area :comment, :size => "30x2" %>
  </div>

  <div class="field">
    <%= f.submit "編集する" %>
  </div>

  <div class="field">
    <%= link_to "一覧に戻る", posts_path %>
  </div>
<% end %>

app/views/posts/food.html.erb
<%= stylesheet_link_tag 'index', :media => "all" %>

<h1>ごはん</h1>

<div class="posts-container">
<% @posts.each do |t| %>
  <% if t.category == "food" %>  
     <div class="post">
     <div class="image">
       <%= t.user.email %>
       <%= image_tag t.image_url, size: "280x210" if t.image? %>
     </div> 
     <%= t.category %>
     <%= t.place %>
     <%= t.create_date %>
     <%= t.comment %>
     <% t.tags.each do |tag| %>
       <span><%= tag.name %></span>
     <% end %>

     <p><%= link_to "詳細へ", post_path(t.id) %> 

     <% if user_signed_in? && current_user.id == t.user_id %>
     <%= link_to "編集する", edit_post_path(t.id) %>
     <%= button_to "削除する", post_path(t.id), method: :delete %> 
    <% end %> 

    <% if user_signed_in? %>
        <% if current_user.already_liked?(t) %>
          <%= link_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
              <i class="fas fa-heart"></i><%= t.likes.count %>
          <% end %>
        <% else %>
          <%= link_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
            <i class="far fa-heart"></i><%= t.likes.count %>
          <% end %>
        <% end %>
    <% else %>
      <i class="far fa-heart"></i><%= t.likes.count %>
    <% end %>

    </div>

  <% end %>

<% end %>

app/views/posts/index.html.erb
<%= stylesheet_link_tag 'index', :media => "all" %>

<h3>一覧ページ</h3>

  <%= link_to "新規投稿へ", new_post_path %>
  <%= link_to "お店", posts_store_path %>
  <%= link_to "ごはん", posts_food_path %>
  <%= link_to "動物", posts_animal_path %>

<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
<% end %>

<div class="posts-container">
  <% @posts.each do |t| %>
   <div class="post">
   <div class="image">
   <%= image_tag t.image_url, size: "280x210" if t.image? %>
   </div> 
   <h4>〈ユーザー名〉</h4><%= t.user.email %>
   <h4>〈カテゴリー〉</h4><%= t.category %>
   <h4>〈場所〉</h4><%= t.place %>
   <h4>〈作成日〉</h4><%= t.create_date %>
   <h4>〈コメント〉</h4><%= t.comment %>

   <p><%= link_to "詳細へ", post_path(t.id) %> 

    <% if user_signed_in? && current_user.id == t.user_id %>
    <%= link_to "編集する", edit_post_path(t.id) %>
    <%= button_to "削除する", post_path(t.id), method: :delete %> 
    <% end %> 

    <% if user_signed_in? %>
        <% if current_user.already_liked?(t) %>
           <%= link_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
              <i class="fas fa-heart"></i><%= t.likes.count %>
           <% end %>
       <% else %>
          <%= link_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
             <i class="far fa-heart"></i><%= t.likes.count %>
          <% end %>
       <% end %>
   <% else %>
       <i class="far fa-heart"></i><%= t.likes.count %>
   <% end %>

   </div>
   <% end %>

</div>

 <div class="aaaaa">
 </div>

app/views/posts/new.html.erb
<%= stylesheet_link_tag 'new', :media => "all" %>

<h2>新規投稿</h2>
<%= form_for @post do |f| %>

  <div class="form-group">
    <%= f.label :content,"ジャンル" %>
    <%= f.select :category, [["お店", "store"], ["ごはん", "food"], ["動物", "animal"]], include_blank: "どの投稿？" %>
  </div> 

  <div class="field">
    <%= f.label :どこ %>
    <%= f.text_field :place, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :写真 %><br>
    <%= f.file_field :image, class: "image" %>
  </div>
  <div id="image-list"></div>

  <div class="form-group">
    <%= f.label :いつ, class: 'control-label' %>
    <p><%= f.date_select :create_date, class: 'form-control' %></p>
  </div>

  <div class="field">
    <%= f.label :コメント  %>
    <%= f.text_area :comment, :size => "30x2" %>
  </div>

  <div class="field">
    <%= f.submit "投稿する" %>
  </div>
<% end %>

<div class="field">
  <%= link_to "一覧に戻る", posts_path %>
</div>

<script>
// プレビュー表示機能は新規投稿("/new/")か投稿編集("/edit/")ページでのみ有効にする
if (document.URL.match( /new/ ) || document.URL.match( /edit/ )) {
  document.addEventListener('DOMContentLoaded', function(){
    // プレビューを表示するための要素を取得
    const ImageList = document.getElementById('image-list');

    const createImageHTML = (blob) => {
      // 画像を表示するためのdiv要素を生成
      const imageElement = document.createElement('div');
      // 表示する画像を生成
      const blobImage = document.createElement('img');
      // img要素のsrc属性の値をセット
      blobImage.setAttribute('src', blob);

      // 生成したHTMLの要素をブラウザに表示させる
      imageElement.appendChild(blobImage);
      ImageList.appendChild(imageElement);
    };

    document.getElementById('post_image').addEventListener('change', function(e){
      // 画像が表示されている場合のみ、すでに存在している画像を削除する（編集ページ用）
      const imageContent = document.querySelector('img');
      if (imageContent){
        imageContent.remove();
      }

      // 発火したイベントeの中の、targetの中の、filesという配列に格納された画像を変数に代入
      const file = e.target.files[0];
      // 画像のURLを生成
      const blob = window.URL.createObjectURL(file);

      createImageHTML(blob);
    });
  });
}

</script>

app/views/posts/show.html.erb
<h1>詳細</h1>

  <div class="post">
  <div class="image">
  <%= @post.user.email %>
     <%= image_tag @post.image_url, size: "280x210" if @post.image? %>
  </div> 
  <%= @post.category %>
  <%= @post.place %>
  <%= @post.create_date %>
  <%= @post.comment %>
  <% @post.tags.each do |tag| %> 
     <span><%= tag.name %></span>
  <% end %>

   <% if user_signed_in? && current_user.id == @post.user_id %>
   <%= link_to "編集する", edit_post_path(@post.id) %>
   <%= button_to "削除する", post_path(@post.id), method: :delete %> 
   <% end %> 

   <% if user_signed_in? %>
       <% if current_user.already_liked?(@post) %>
          <%= link_to post_like_path(id: @post.id, post_id: @post.id), method: :delete do %>
             <i class="fas fa-heart"></i><%= @post.likes.count %>
          <% end %>
      <% else %>
         <%= link_to post_likes_path(id: @post.id, post_id: @post.id), method: :post do %>
            <i class="far fa-heart"></i><%= @post.likes.count %>
         <% end %>
      <% end %>
  <% else %>
      <i class="far fa-heart"></i><%= @post.likes.count %>
  <% end %>

  </div>

<h2>いいねしたユーザー</h2>
<% @post.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>

<%= link_to "一覧に戻る", posts_path %>

app/views/posts/store.html.erb
<link rel="stylesheet" type="text/css" href="index.css">

<h1>お店</h1>

<div class="posts-container">
<% @posts.each do |t| %>
  <% if t.category == "store" %>  

     <div class="post">
     <div class="image">
       <%= t.user.email %>
       <%= image_tag t.image_url, size: "280x210" if t.image? %>
     </div> 
     <%= t.category %>
     <%= t.place %>
     <%= t.create_date %>
     <%= t.comment %>
     <% t.tags.each do |tag| %>
       <span><%= tag.name %></span>
     <% end %>

     <% if user_signed_in? && current_user.id == t.user_id %>
     <%= link_to "編集する", edit_post_path(t.id) %>
     <%= button_to "削除する", post_path(t.id), method: :delete %> 
    <% end %> 

    <p><%= link_to "詳細へ", post_path(t.id) %> 

    <% if user_signed_in? %>
        <% if current_user.already_liked?(t) %>
          <%= link_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
              <i class="fas fa-heart"></i><%= t.likes.count %>
          <% end %>
        <% else %>
          <%= link_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
            <i class="far fa-heart"></i><%= t.likes.count %>
          <% end %>
        <% end %>
    <% else %>
      <i class="far fa-heart"></i><%= t.likes.count %>
    <% end %>

    </div>

  <% end %>

<% end %>

app/views/posts/top.html.erb
<!DOCTYPE html> 
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>散歩</title>
    <link rel="stylesheet" type="text/css" href="stylesheets/top.scss">
  </head>

  <body>
  <%= image_tag 'IMG_9094.JPG', size: '1440x700' %>

  <div class="flex">

  <div class="right">
    <p class="title">このサイトに関して</p>
    <p class="text">皆さん、お気に入りの場所はありませんか？このサイトでは、地図には載っていない場所、載っているけれど注目を浴びていない部分に焦点を当てたサイトです。</p>
  </div>
  <%= image_tag '7F27039C-A7D3-4272-B3B4-97BAB3B69A5A.png', size: '500x500' , class: 'hoge1' %>
</div>

  <div class="flex">
  <%= image_tag '43A6F14F-280A-470A-A109-985A1570C72F.png', size: '500x500' , class: 'hoge2' %>
  <div class="left">
    <p class="title">利用に関して</p>
    <p class="text">皆さんのおすすめの場所を、文章や写真を使ってぜひ投稿してみてください。</p>
  </div>
</div>

  <h3>他のページ</h3>
    <%= link_to "新規投稿へ", new_post_path %>
    <%= link_to "投稿一覧へ", posts_path %>
    <%= link_to "お店", posts_store_path %>
    <%= link_to "ごはん", posts_food_path %>
    <%= link_to "動物", posts_animal_path %>
  <div class="posts-container">
  
  <% if user_signed_in? %>
    <%= link_to "マイページへ", user_path(current_user.id) %>
  <% end %>

  </body>

  </html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<%= stylesheet_link_tag 'users', :media => "all" %>

<h1>マイページ</h1>

<div class="field">
  <p>名前 : <%= @user.name %></p>
  <p>メールアドレス : <%= @user.email %></p>
  <p>プロフィール : <%= @user.profile %></p>
</div>

<% if current_user.id == @user.id %>
<div class="field">
  <%= link_to "編集する", edit_user_registration_path %>
</div> 
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.posts.each do |t| %>
  <div class="post">
  <div class="image">
  <%= t.user.email %>
     <%= image_tag t.image_url, size: "280x210" if t.image? %>
  </div> 
  <%= t.category %>
  <%= t.place %>
  <%= t.create_date %>
  <%= t.comment %>
  <% t.tags.each do |tag| %>
  <%= link_to "詳細へ", post_path(t.id) %>  
     <span><%= tag.name %></span>
  <% end %>

   <% if user_signed_in? && current_user.id == t.user_id %>
   <%= link_to "編集する", edit_post_path(t.id) %>
   <%= button_to "削除する", post_path(t.id), method: :delete %> 
   <% end %> 

   <% if user_signed_in? %>
       <% if current_user.already_liked?(t) %>
          <%= link_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
             <i class="fas fa-heart"></i><%= t.likes.count %>
          <% end %>
      <% else %>
         <%= link_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
            <i class="far fa-heart"></i><%= t.likes.count %>
         <% end %>
      <% end %>
  <% else %>
      <i class="far fa-heart"></i><%= t.likes.count %>
  <% end %>

<div class="field">
  <%= t.user.name %>
  <%= t.place %>
</div>
<% end %>

<div class="field">
  <%= link_to "投稿一覧に戻る", posts_path %>
</div>